name: Build with MCU Expresso

on:
  push:
    branches: [ develop ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'

      - name: Generate Build defines
        run: |
          MY_SWVERSION=$(printf 'SW-%.8s' "${{ github.sha }}" )
          echo '\n#define BUILD_SWVERSION "$MY_SWVERSION"\n' >> src/build.h
          echo "MY_SWVERSION=$MY_SWVERSION" >> $GITHUB_ENV
          cat src/build.h
          pwd
          
      - name: Build the mcu workspace
        uses: RobertK66/actions-build-mcuxpresso@main
        id: publish-document
        with:
          project:  ClimbObc
          
      - name: Upload Binary
        uses: actions/upload-artifact@v2
        id: upload-axf
        with:
          name: 'obc-axf-{{ env.MY_SWVERSION }}'
          path: ${{ steps.publish-document.outputs.axf }}
          if-no-files-found: error
          
