name: Build with MCU Expresso

on:
  push:
    branches: [ develop ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'

      - name: Generate Build defines
        run: |
          MYSWVERSION=$(printf '\n#define BUILD_SWVERSION "SW-%.8s"\n' "${{ github.sha }}" )
          echo $MYSWVERSION >> src/build.h
          cat src/build.h
          
      - name: Build the mcu workspace
        uses: RobertK66/actions-build-mcuxpresso@main
        id: publish-document
        with:
          project:  ClimbObc
          
      - name: Upload Binary
        uses: actions/upload-artifact@v2
        id: upload-axf
        with:
          name: 'obc-axf'
          path: ${{ steps.publish-document.outputs.axf }}
          if-no-files-found: error
          
