on:
  push:
    branches: [ develop ]
    paths-ignore:
      - '.github/**'
  release:
    types: [created]
  workflow_dispatch:

jobs:
  prepBuild:
    runs-on: ubuntu-latest
    name: Prepare Build Variables
    steps:
      - run: |
          ls -al
          echo hello 1
      
  buildIt:
    runs-on: ubuntu-latest
    needs: prepBuild
    name: Build the Software artefacts
    steps:
      - run: |
          ls -al
          echo hello 2
