

name: Convert MD dcumentation to PDF  

on:
  push:
    branches: [ master ]
    paths:
      - 'doc/**'
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
          
      # first try -> current version does not work, old version 'geoffrey....' does but images not there.....
      #- name: Create PDF
      #  # You may pin to the exact commit or the version.
      #  uses: geoffrey-vl/actions-makepdfs@e14cca39763dc833d20fd40b2a1941196cb27716 
      #  #uses: mkrakowitzer/actions-makepdfs@07f1b3912a5dbcd72fe0feed3a3047a17c976d5e
      #  #uses: mkrakowitzer/actions-makepdfs@master
      #  with:
      #    # Location of markdown files in github repository
      #    markdown_dir: doc # default is doc
      #    # Location to output PDF files to
      #    # output_dir: # default is tmp
      #    # media_dir: /doc/pic

      #- uses: actions/upload-artifact@v1
      #  with:
      #    name: obc-docs
      #    path: tmp
       
      # 2nd try -> works fine but no doku on how to get images included....
      #- name: Publish PDF Document
      #  uses: shrink/actions-document-publish@v1
      #  id: publish-document
      #  with:
      #    sources: 'doc/front.md doc/*.md doc/back.md'
      #    
      #- name: Upload Document
      #  uses: actions/upload-artifact@v2
      #  id: upload-document
      #  with:
      #    name: 'document.pdf'
      #    path: ${{ steps.publish-document.outputs.pdf }}

      # 3rd try. this works fine but no single file output....
      #- uses: baileyjm02/markdown-to-pdf@v1
      #  with:
      #    input_dir: doc
      #    output_dir: pdfs
      #    images_dir: doc/pic
      #    # for example <img src="./images/file-name.png">
      #    image_import: pic
      #    # Default is true, can set to false to only get PDF files
      #    build_html: false
      #    
      #- uses: actions/upload-artifact@v1
      #  with:
      #    name: docs
      #    path: pdfs

      # 4th try -> can I clone shrinks version and simply pass in the image feature variables....
      - name: Publish PDF Document
        uses: RobertK66/actions-document-publish@79d61444458a6db638b273bc6b50053f14ca86e2
        id: publish-document
        with:
          sources: 'doc/front.md doc/*.md doc/back.md'
          
      - name: Upload Document
        uses: actions/upload-artifact@v2
        id: upload-document
        with:
          name: 'document.pdf'
          path: ${{ steps.publish-document.outputs.pdf }}
